const TWITTER_TOKENS = {
  TWITTER_API_KEY: "sZvM36DTa8kg6FWlflN5m07Z3",
  //   TWITTER_CONSUMER_SECRET: "SOME SECRET",
  TWITTER_BEARER_TOKEN: "NKmUsax7EQJygskw3fT7qkp0DhkSgNLv7X0nCXxEgnyCwrhafv",
  TWITTER_TOKEN_SECRET:
    "AAAAAAAAAAAAAAAAAAAAAPkucAEAAAAAo6MvvRoV3wpvPDTXxtNeky2jsRk%3DTTIjyZAmOiic5RnFmk1LIh58q0pbEkTmUN61UW4Ri2jny3vqE4",
};

module.exports = KEYS;
